# Generated by Django 3.2.5 on 2021-08-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('DailyInterestRate', models.FloatField()),
                ('MonthlyInterestRate', models.FloatField()),
                ('EmailAddress', models.EmailField(max_length=250)),
                ('PhoeNumber', models.CharField(max_length=250)),
                ('VerificationStatus', models.CharField(max_length=32)),
                ('InstitutionalStatus', models.CharField(max_length=32)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
