# Generated by Django 3.2.5 on 2021-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstitution',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
