# Generated by Django 3.2.5 on 2021-08-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_institute', '0002_alter_financialinstitution_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialinstitution',
            old_name='PhoeNumber',
            new_name='PhoneNumber',
        ),
    ]
