# Generated by Django 3.2.5 on 2021-11-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211129_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='323159dbe5c848608f4f5f3c1bfe4486', editable=False, unique=True),
        ),
    ]
