# Generated by Django 3.2.5 on 2021-11-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='d360ebf5248e4ef5924fced4aeac2563', editable=False, unique=True),
        ),
    ]
