# Generated by Django 3.2.5 on 2021-11-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='86b062c1e67844a0af21f7956d6c78df', editable=False, unique=True),
        ),
    ]
