# Generated by Django 3.2.5 on 2021-11-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='51d6549605ed48049661923429af1501', editable=False, unique=True),
        ),
    ]
