# Generated by Django 3.2.5 on 2021-12-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='d60d06e9bc7943c7b2b0db30e6187c16', editable=False, unique=True),
        ),
    ]
