# Generated by Django 3.2.5 on 2021-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='16acf6d4b117435dbf0490f339850910', editable=False, unique=True),
        ),
    ]
