# Generated by Django 3.2.5 on 2021-12-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='263aa0706a094b92a28ef671513f8a95', editable=False, unique=True),
        ),
    ]
