# Generated by Django 3.2.5 on 2021-12-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='9187db7ff5ad47f2915f2e75edf0eaa6', editable=False, unique=True),
        ),
    ]
