# Generated by Django 3.2.5 on 2021-12-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='a8f52b903f0f4084a2b1b3b0384e9bd1', editable=False, unique=True),
        ),
    ]
