# Generated by Django 3.2.5 on 2021-12-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='fb1fb1e5fa8849b68c152d9d1e7965d4', editable=False, unique=True),
        ),
    ]
