# Generated by Django 3.2.5 on 2021-12-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='0e256dd2a3f846efa9dc7a1b6122bdb1', editable=False, unique=True),
        ),
    ]
