# Generated by Django 3.2.5 on 2022-01-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='1ced4464aafb4e72bf9a7bb49207dd06', editable=False, unique=True),
        ),
    ]
