# Generated by Django 3.2.5 on 2022-01-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='88748ff1ed144d76abf346b5f4fdf9b7', editable=False, unique=True),
        ),
    ]
