# Generated by Django 3.2.5 on 2022-01-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='49602eadb51b42bba20b5c1260f666d5', editable=False, unique=True),
        ),
    ]
