# Generated by Django 3.2.5 on 2022-01-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='a7f32fa4d8954f74a7fb5913d9a44666', editable=False, unique=True),
        ),
    ]
