# Generated by Django 3.2.5 on 2022-01-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='bcace46024f64738acb7f5f7a5b3cde0', editable=False, unique=True),
        ),
    ]
