# Generated by Django 3.2.5 on 2022-01-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='0308be3ee71946cdb152c13f2e12956c', editable=False, unique=True),
        ),
    ]
