# Generated by Django 3.2.5 on 2022-01-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='f1919db2fdff430192c2e10e228f1a08', editable=False, unique=True),
        ),
    ]
