# Generated by Django 3.2.5 on 2022-01-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='ffeb802a44b34f36b42a1c6f7b539ec2', editable=False, unique=True),
        ),
    ]
