# Generated by Django 3.2.5 on 2022-01-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='06007619329d431fac3a501e73f67599', editable=False, unique=True),
        ),
    ]
