# Generated by Django 3.2.5 on 2022-01-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='be07612298cf478aa703d48d39073933', editable=False, unique=True),
        ),
    ]
