# Generated by Django 3.2.5 on 2022-01-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='b56b2daebb8445368ee2ee51c82aca88', editable=False, unique=True),
        ),
    ]
