# Generated by Django 3.2.5 on 2022-01-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='cad42ef4a60944cd9d585241c02d30b3', editable=False, unique=True),
        ),
    ]
