# Generated by Django 3.2.5 on 2022-01-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='9a1629004b9640eeac422a5120d97513', editable=False, unique=True),
        ),
    ]
