# Generated by Django 3.2.5 on 2022-01-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='d09aada85f52412aac0e7f0cd888f798', editable=False, unique=True),
        ),
    ]
