# Generated by Django 3.2.5 on 2022-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='f67e683fd83b4dc092cbc00ce4a424de', editable=False, unique=True),
        ),
    ]
