# Generated by Django 3.2.5 on 2022-02-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0043_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='427af3686e9143abb9f2edd8592eaf1b', editable=False, unique=True),
        ),
    ]
