# Generated by Django 3.2.5 on 2022-02-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='b9d5d10b4a2b461f82b47419bab6fdc8', editable=False, unique=True),
        ),
    ]
