# Generated by Django 3.2.5 on 2021-08-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0003_auto_20210811_0900'),
        ('financial_institute', '0003_rename_phoenumber_financialinstitution_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('withdrew_on', models.CharField(max_length=200)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
            ],
        ),
        migrations.CreateModel(
            name='WalletDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('deposited_when', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_institute.financialinstitution')),
            ],
        ),
    ]
