# Generated by Django 3.2.5 on 2021-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_walletwithdraw_withdrew_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('party', models.CharField(max_length=200)),
                ('transacted_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
