# Generated by Django 3.2.5 on 2021-09-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallettransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletdeposit',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='walletwithdraw',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
