# Generated by Django 3.2.5 on 2021-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20210909_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletwithdraw',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
