# Generated by Django 3.2.5 on 2022-01-16 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_loans_loan_uid'),
        ('wallet', '0005_alter_walletwithdraw_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('request_id', models.CharField(max_length=100)),
                ('correlation_id', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans')),
            ],
        ),
    ]
