# Generated by Django 3.2.5 on 2022-01-16 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_rename_transactions_loantransactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantransactions',
            old_name='created_on',
            new_name='transaction_created_on',
        ),
        migrations.AddField(
            model_name='loantransactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
