# Generated by Django 3.2.5 on 2022-02-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20220116_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransactions',
            name='transaction_status',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
