# Generated by Django 3.2.5 on 2021-08-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_product', models.CharField(choices=[('Business Loan', 'Business Loan'), ('Student Loan', 'Student Loan')], max_length=100)),
                ('disbursed_by', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=100)),
                ('principal_amount', models.IntegerField()),
                ('loan_release_date', models.DateTimeField()),
                ('interest_rate', models.FloatField()),
                ('loan_duration', models.IntegerField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrower')),
            ],
        ),
    ]
