# Generated by Django 3.2.5 on 2021-11-25 10:54

from django.db import migrations, models
import django.db.models.deletion
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20210811_0900'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_request_uid', models.CharField(default=loans.models.loan_rand, max_length=20)),
                ('name_of_requestor', models.CharField(max_length=200)),
                ('loan_amount', models.IntegerField()),
                ('loan_purpose', models.TextField()),
                ('loan_duration', models.IntegerField()),
                ('loan_request_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
            ],
        ),
    ]
