# Generated by Django 3.2.5 on 2021-11-25 12:02

from django.db import migrations, models
import django.db.models.deletion
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0002_borrower_tn'),
        ('loans', '0002_loanrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='name_of_requestor',
            new_name='borrower_id',
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_request_uid',
            field=models.CharField(default=loans.models.loan_rand, editable=False, max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default='pb_100', max_length=20)),
                ('amount_paid', models.IntegerField()),
                ('when_paid', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrower')),
            ],
        ),
    ]
