# Generated by Django 3.2.5 on 2021-11-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='disbursed_by',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='loan_product',
        ),
    ]
