# Generated by Django 3.2.5 on 2021-11-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_auto_20211125_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_request_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
