# Generated by Django 3.2.5 on 2021-11-29 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loanrequest_loan_request_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_status', models.CharField(choices=[('received', 'received'), ('pending', 'pending'), ('approved', 'approved'), ('disapproved', 'disapproved')], default=1, max_length=50)),
                ('loan_status_description', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loans')),
            ],
        ),
    ]
