# Generated by Django 3.2.5 on 2021-11-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_rename_borrower_id_loanrequest_channel_borrower_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequeststatus',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_request', to='loans.loanrequest'),
        ),
    ]
