# Generated by Django 3.2.5 on 2021-12-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_alter_loanrequeststatus_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequeststatus',
            name='loan_status',
            field=models.CharField(choices=[('received', 'received'), ('pending', 'pending'), ('approved', 'approved'), ('disapproved', 'disapproved')], default='received', max_length=50),
        ),
    ]
