# Generated by Django 3.2.5 on 2021-12-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_alter_loanrequeststatus_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequeststatus',
            name='loan_status',
            field=models.CharField(choices=[('received', 'received'), ('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='received', max_length=50),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_release_date',
            field=models.DateField(),
        ),
    ]
