# Generated by Django 3.2.5 on 2021-12-15 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_auto_20211215_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_due_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
