# Generated by Django 3.2.5 on 2022-01-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_loans_loan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Paid', 'Paid'), ('Canceled', 'Canceled')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
