# Generated by Django 3.2.5 on 2022-01-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_loans_loan_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='trnsaction_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
