# Generated by Django 3.2.5 on 2022-01-26 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_payment_trnsaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequeststatus',
            name='loan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_request', to='loans.loanrequest'),
        ),
    ]
