# Generated by Django 3.2.5 on 2022-01-27 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_alter_loanrequeststatus_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_request_uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20),
        ),
    ]
