# Generated by Django 3.2.5 on 2022-01-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_alter_loanrequest_loan_request_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='channel_borrower_uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
