# Generated by Django 3.2.5 on 2022-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0022_alter_loans_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='when_paid',
            field=models.DateTimeField(),
        ),
    ]
