# Generated by Django 3.2.5 on 2022-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0023_alter_payment_when_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='loan_status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Paid', 'Paid'), ('Defaulted', 'Defaulted')], default='Issued', max_length=100),
        ),
    ]
