# Generated by Django 3.2.5 on 2021-11-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0005_alter_borrower_borrower_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='channel_borrower_id',
            new_name='channel_borrower_uid',
        ),
    ]
