# Generated by Django 3.2.5 on 2022-02-12 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0007_alter_borrower_tn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrower_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='channel_borrower_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
