# Generated by Django 3.2.5 on 2021-08-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChannelName', models.CharField(max_length=250)),
                ('Logo', models.ImageField(upload_to='')),
                ('WebHook', models.CharField(max_length=250)),
                ('EmailAddress', models.EmailField(max_length=250, unique=True)),
                ('PhoneNumber', models.CharField(max_length=25)),
                ('ShortDescription', models.TextField(max_length=250)),
                ('LongDescription', models.TextField(max_length=512)),
                ('DeactivatedOn', models.DateTimeField()),
                ('ApiKey', models.CharField(max_length=36)),
            ],
        ),
    ]
