# Generated by Django 3.2.5 on 2021-08-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='Logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
