# Generated by Django 3.2.5 on 2021-08-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='DeactivatedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
