# Generated by Django 3.2.5 on 2022-01-22 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20210811_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ApiKey',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
