# Generated by Django 3.2.5 on 2022-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_alter_channel_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ApiKey',
            field=models.UUIDField(default='7d7e125f2b7a472288e4deef1536861d', editable=False),
        ),
    ]
