# Generated by Django 3.2.5 on 2022-01-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_alter_channel_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ApiKey',
            field=models.UUIDField(default='dd759adbd16649d09e9df9b3b9b1840d', editable=False),
        ),
    ]
