# Generated by Django 3.2.5 on 2022-01-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0010_alter_channel_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ApiKey',
            field=models.UUIDField(default='1d603adc4f0d4601a6b42ec01c7a4f4f', editable=False),
        ),
    ]
