# Generated by Django 3.2.5 on 2022-01-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0013_alter_channel_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ApiKey',
            field=models.UUIDField(default='15f74524e98c49b3acfb62a6913a5e3e', editable=False),
        ),
    ]
