# Generated by Django 3.2.5 on 2022-01-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0014_alter_channel_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ApiKey',
            field=models.UUIDField(default='28df0fcd9b344de98c87621a78b31e82', editable=False),
        ),
    ]
