# Generated by Django 3.2.5 on 2022-02-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0015_alter_channel_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ApiKey',
            field=models.UUIDField(default='f432875a4bda48b2ad7dabf60547fb07', editable=False),
        ),
    ]
