# Generated by Django 3.2.5 on 2022-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0017_alter_channel_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ApiKey',
            field=models.UUIDField(default='06bd24f41faf424991b88edfecf88a83', editable=False),
        ),
    ]
