# Generated by Django 3.2.5 on 2022-02-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0018_alter_channel_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ApiKey',
            field=models.UUIDField(default='2e73418779ad4688ac55dc478a9f9fd4', editable=False),
        ),
    ]
