# Generated by Django 3.2.5 on 2022-02-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0019_alter_channel_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ApiKey',
            field=models.UUIDField(default='fcdc1a9aeba94e4285bc5e9cdebff556', editable=False),
        ),
    ]
