# Generated by Django 3.2.5 on 2022-02-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0020_alter_channel_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ApiKey',
            field=models.UUIDField(default='6b0ad11201da47a29d1348ec415b067e', editable=False),
        ),
    ]
