# Generated by Django 3.2.5 on 2021-08-11 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('InstitutionalLimit', models.DecimalField(decimal_places=4, max_digits=13)),
                ('RevolvingLimit', models.DecimalField(decimal_places=4, max_digits=13)),
                ('DailyInterestRate', models.FloatField()),
                ('MonthlyInterestRate', models.FloatField()),
                ('Logo', models.ImageField(upload_to='')),
                ('Description', models.TextField()),
                ('TrustNetworkCategory', models.CharField(max_length=32)),
                ('RequiresApproval', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10)),
                ('RequiredApproval', models.CharField(max_length=32)),
                ('Domains', models.TextField()),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
            ],
        ),
    ]
