# Generated by Django 3.2.5 on 2021-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustnetwork',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
