# Generated by Django 3.2.5 on 2021-11-23 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trust_network', '0002_alter_trustnetwork_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustnetwork',
            name='CreatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trustnetwork',
            name='DailyInterestRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trustnetwork',
            name='Domains',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trustnetwork',
            name='InstitutionalLimit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='trustnetwork',
            name='MonthlyInterestRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trustnetwork',
            name='RequiredApproval',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='trustnetwork',
            name='RequiresApproval',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trustnetwork',
            name='RevolvingLimit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='trustnetwork',
            name='TrustNetworkCategory',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
