# Generated by Django 3.2.5 on 2021-12-10 12:53

from django.db import migrations, models
import trust_network.models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_network', '0003_auto_20211123_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustnetwork',
            name='trustnetwork_uid',
            field=models.CharField(blank=True, default=trust_network.models.tn_rand, max_length=100, null=True),
        ),
    ]
