# Generated by Django 3.2.5 on 2021-12-10 12:54

from django.db import migrations, models
import trust_network.models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_network', '0004_trustnetwork_trustnetwork_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustnetwork',
            name='trustnetwork_uid',
            field=models.CharField(default=trust_network.models.tn_rand, max_length=100),
        ),
    ]
