# Generated by Django 3.2.5 on 2022-01-22 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trust_network', '0006_trustnetworkstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustnetwork',
            name='RequiredApproval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_approval', to=settings.AUTH_USER_MODEL),
        ),
    ]
